### ISSUE TITLE
Release 2.0.0-rc1 roadmap

### ISSUE THREAD

**Issue by dmolineus** [netzmacht/contao-workflow#8]
- [x] Stable release of netzmacht/contao-form-bundle
- [x] Update readme
- [x] Setup basic documentation
- [x] Add changelog
- [x] Provide customization examples (#7)

**Comment by dmolineus** [comment]
Just released version 2.0.0-rc1.
